<fieldset class="fieldset">
    <legend>Popunite tražene podatke</legend>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'naziv','Naziv obrade');?>
    
    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'izvodac','Naziv izvođača');?>

    <?php echo Utility::inputText(
        isset($greska) ? $greska : null,'url','URL obrade');?>

<label for="zanr">Žanr</label>
        <select name="zanr" id="zanr">
            <option value="0">Odaberite žanr</option>
            <?php foreach($zanrovi as $zanr): ?>
                <option 
                
                <?php echo App::param("zanr")==$zanr->sifra ? 'selected="selected"' : ''; ?>
                
                value="<?php echo $zanr->sifra; ?>">
                    <?php echo $zanr->naziv; ?>
                </option>
        <?php endforeach; ?>
        </select>
    
    <label for="datumpocetka">Datum početka</label>
    <input type="date" name="datum" id="datum" 
    value="<?php echo App::param("datum") ?>"/>

</fieldset>
<hr />