<a href="<?php echo App::config("url") ?>obrada/pripremaNovi" 
class=" button expanded">
<i class="fas fa-plus-square"></i>
Dodaj novu obradu</a>

<table id="tablicaObrade">
  <thead>
    <tr>
     <th>Naziv</th>
     <th>Originalni izvođač</th>
     <th>Datum</th>
     <th>Žanr</th>
     <th>Akcija</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($obrade as $obrada): ?>
      <tr>
        <td><?php echo $obrada->obrada?></td>
        <td><?=$obrada->izvodac?></td>
        <td><?php echo date("d. m. Y.",strtotime($obrada->datum));?></td>
        <td><?php echo $obrada->zanr?></td>
        <td>
        <a title="Promjeni <?php echo $obrada->obrada ?>" 
            href="<?php 
            echo App::config("url") 
            ?>obrada/pripremaPromjeni/<?php echo $obrada->sifra ?>">
            <i class="fas fa-edit fa-2x" style="color: orange"></i>
        </a>
        <?php if($obrada->ukupno==0): ?>
            <a title="Obriši <?php echo $obrada->obrada ?>" 
                onclick="return confirm('Sigurno obrisati <?php echo $obrada->obrada ?>?');"
                href="<?php 
                echo App::config("url") 
                ?>obrada/brisanje/<?php echo $obrada->sifra ?>">
                <i class="fas fa-trash fa-2x" style="color: red"></i>
            </a>
    <?php else:?>
            <i title="Ne može se obrisati jer ima glazbenike" 
            class="fas fa-trash fa-2x" style="color: gray"></i>

        <?php endif;?>
        
        </td>
      </tr>
    <?php endforeach;?>
  </tbody>
</table>