<div class="grid-x grid-margin-x">
    <div class="cell large-6">
        <form method="post" 
            action="<?php echo App::config("url")?>obrada/promjeni/<?php echo $id ?>">
                <?php include_once 'detalji.phtml' ?>
                <div class="grid-x">
                    <div class="large-3 small-5 column">
                        <a class="alert button expanded"
                            href="<?php echo App::config("url")?>obrada/index">
                            Odustani
                        </a>
                    </div>
                    <div class="large-1 small-1 column">
                        
                    </div>
                    <div class="large-8 small-6 column">
                        <input class="button expanded"
                            type="submit" value="Promjena">
                    </div>
                </div>
        </form>
    </div>
    <div>
    <label for="glazbenik">Glazbenik</label>
        <select name="glazbenik" id="glazbenik">
            <option value="0">Odaberite glazbenika</option>
            <?php foreach($glazbenici as $glazbenik): ?>
                <option 
                
                <?php echo App::param("zanr")==$glazbenik->sifra ? 'selected="selected"' : ''; ?>
                
                value="<?php echo $glazbenik->sifra; ?>">
                    <?php echo $glazbenik->ime . " " 
                            . $glazbenik->prezime; ?>
                </option>
        <?php endforeach; ?>
       </select> 

    <label for="instrument">Instrument</label>
        <select name="instrument" id="instrument">
            <option value="0">Odaberite instrument</option>
            <?php foreach($instrumenti as $instrument): ?>
                <option 
                
                <?php echo App::param("instrument")==$instrument->sifra ? 'selected="selected"' : ''; ?>
                
                value="<?php echo $instrument->sifra; ?>">
                    <?php echo $instrument->ime; ?>
                </option>
        <?php endforeach; ?> 
        </select>
       </div>    
</div>